// <auto-generated />
using System;
using ERP.DAL.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP.DAL.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260129171139_AddProjectModule")]
    partial class AddProjectModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERP.DAL.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 100L);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("Cast(GETUTCDATE() as Date)");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("Latin1_General_CI_AS");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Departments_DepartmentCode_Unique")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ManagerId")
                        .IsUnique()
                        .HasDatabaseName("IX_Departments_ManagerId_Unique")
                        .HasFilter("[ManagerId] IS NOT NULL AND [IsDeleted] = 0");

                    b.ToTable("Departments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Department_DepartmentCode_Format", "DepartmentCode LIKE '[A-Z][A-Z][A-Z]_[0-9][0-9][0-9]'");
                        });
                });

            modelBuilder.Entity("ERP.DAL.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1000L);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("Cast(GETUTCDATE() as Date)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("date");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Employees_Email_Unique")
                        .HasFilter("[IsDeleted] = 0")
                        .HasAnnotation("Relational:Collation", "Latin1_General_CI_AS");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("IsActive", "IsDeleted");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("ERP.DAL.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1000L);

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("Cast(GETUTCDATE() as Date)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("Latin1_General_CI_AS");

                    b.Property<int?>("ProjectManagerId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ProjectCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Projects_ProjectCode_Unique")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("ProjectManagerId")
                        .IsUnique()
                        .HasDatabaseName("IX_Projects_ProjectManagerId_Unique")
                        .HasFilter("[ProjectManagerId] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("Status", "DepartmentId", "IsDeleted");

                    b.ToTable("Projects", null, t =>
                        {
                            t.HasCheckConstraint("CK_Project_ProjectCode_Format", "ProjectCode LIKE 'PRJ-[0-9][0-9][0-9][0-9]-[0-9][0-9][0-9]'");
                        });
                });

            modelBuilder.Entity("ERP.DAL.Models.Department", b =>
                {
                    b.HasOne("ERP.DAL.Models.Employee", "Manager")
                        .WithOne("ManagedDepartment")
                        .HasForeignKey("ERP.DAL.Models.Department", "ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("ERP.DAL.Models.Employee", b =>
                {
                    b.HasOne("ERP.DAL.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ERP.DAL.Models.Project", b =>
                {
                    b.HasOne("ERP.DAL.Models.Department", "Department")
                        .WithMany("Projects")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.DAL.Models.Employee", "ProjectManager")
                        .WithOne("ManagedProject")
                        .HasForeignKey("ERP.DAL.Models.Project", "ProjectManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("ProjectManager");
                });

            modelBuilder.Entity("ERP.DAL.Models.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ERP.DAL.Models.Employee", b =>
                {
                    b.Navigation("ManagedDepartment");

                    b.Navigation("ManagedProject");
                });
#pragma warning restore 612, 618
        }
    }
}
